#生产环境配置
server:
  port: 8081

springdoc:
  api-docs:
    enabled: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
#  influx:
#    url: http://localhost:8086
#    user: admin
#    password: 12345678
  mail:
    host: smtp.126.com
    username: your_email@126.com
    password: your_email_password

  rabbitmq:
    addresses: localhost
    username: your_rabbitmq_username
    password: your_rabbitmq_password
    virtual-host: /
  datasource:
    url: jdbc:mysql://localhost:3306/monitor
    username: your_mysql_username
    password: your_mysql_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    jwt:
      key: 'abcdefghijklmn'
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
    flow:
      period: 5
      limit: 100
      block: 30
    cors:
      origin: 'http://localhost:5173'
      credentials: false
      methods: '*'
